<?php
if ( ! function_exists( 'wildnest_customizer_styling_config' ) ) {
	function wildnest_customizer_styling_config( $configs ) {
		$wildnest_buttons = wildnest_get_customizer_buttons_styling();
		$wildnest_buttons_hover = wildnest_get_customizer_buttons_hover_styling();
		$wildnest_fields = wildnest_get_customizer_fields_styling();
		$wildnest_fields_focus = wildnest_get_customizer_fields_styling_focus();
		$section = 'wildnest_styling_settings';
		$config = array(
			array(
				'name'     => 'styling_settings_panel',
				'type'     => 'panel',
				'priority' => 22,
				'title'    => esc_html__( 'Styling Settings', 'wildnest' ),
			),

			// I.General Tab
			array(
				'name'  => "wildnest_styling_settings_color",
				'type'  => 'section',
				'panel' => 'styling_settings_panel',
				'title' => esc_html__( 'General Site Styling', 'wildnest' ),
			),
			array(
				'name'    		=> 'wildnest_styling_body_color_h',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_color',
				'title'   		=> esc_html__( 'Body Styling', 'wildnest' ),
			),
			array(
				'name'            => 'wildnest_styling_body_width',
				'type'            => 'slider',
				'section'         => 'wildnest_styling_settings_color',
				'default'         => array('desktop'=>1400),
				'max'             => 1400,
				'device_settings' => true,
				'title'           => esc_html__( 'Site Container Width', 'wildnest' ),
				'selector'        => 'format',
				'css_format'      => ".container, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl { max-width: {{value}} !important; }",
			),
			array(
				'name'       	=> 'wildnest_styling_body_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'		=> '#ffffff',
				'title'      	=> esc_html__( 'Body Background Color', 'wildnest' ),
			),
			array(
				'name'            => 'wildnest_styling_body_img',
				'type'            => 'image',
				'section'         => 'wildnest_styling_settings_color',
				'title'           => esc_html__( 'Body Background Image', 'wildnest' ),
			),

			array(
				'name'    		=> 'wildnest_styling_settings_color_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_color',
				'title'   		=> esc_html__( 'Links Color Option', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_color_links_normal',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'		=> '#222',
				'title'      	=> esc_html__( 'Regular', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_color_links_hover',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'title'      	=> esc_html__( 'Hover', 'wildnest' ),
			),
			array(
				'name'    => 'wildnest_styling_settings_color_links_weight',
				'type'    => 'select',
				'section' => 'wildnest_styling_settings_color',
				'label'   => esc_html__( 'Weight', 'wildnest' ),
				'choices' => array(
					'default'   => esc_html__( 'Default', 'wildnest' ),
					'bold' 		=> esc_html__( 'Bold', 'wildnest' ),
					'100'  		=> esc_html__( '100', 'wildnest' ),
					'200'  		=> esc_html__( '200', 'wildnest' ),
					'300' 		=> esc_html__( '300', 'wildnest' ),
					'400' 		=> esc_html__( '400', 'wildnest' ),
					'500' 		=> esc_html__( '500', 'wildnest' ),
					'600' 		=> esc_html__( '600', 'wildnest' ),
					'700' 		=> esc_html__( '700', 'wildnest' ),
					'800' 		=> esc_html__( '800', 'wildnest' ),
				)
			),

			// 1. Main colors and Background
			array(
				'name'    		=> 'wildnest_styling_settings_color_bg_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_color',
				'title'   		=> esc_html__( 'Main colors & Background', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_color_text_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'   	=> '#2695ff',
				'title'      	=> esc_html__( 'Text color', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_main_bg_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'   	=> '#2695ff',
				'title'      	=> esc_html__( 'Background color', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_main_border_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'   	=> '#2695ff',
				'title'      	=> esc_html__( 'Border color', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_main_bg_color_hover',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'   	=> '#ffffff',
				'title'      	=> esc_html__( 'Background color (hover)', 'wildnest' ),
			),

			// 2. Text selection
			array(
				'name'    		=> 'wildnest_styling_settings_text_selection_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_color',
				'title'   		=> esc_html__( 'Text Selection Color & Background', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_selection_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'   	=> '#ffffff',
				'title'      	=> esc_html__( 'Color', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_selection_bg',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'   	=> 'format',
				'default'   	=> '#2695ff',
				'title'      	=> esc_html__( 'Background color', 'wildnest' ),
			),
			array(
				'name'    		=> 'wildnest_styling_settings_paragraph_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_color',
				'title'   		=> esc_html__( 'Body & Paragraphs Color', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_color_body_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_color',
				'selector'    	=> 'body',
				'css_format' 	=> 'color: {{value}};',
				'default'		=> '#6a6b76',
				'title'      	=> esc_html__( 'Color', 'wildnest' ),
			),

			// 3. Menu Styling Tab
			array(
				'name'  => "wildnest_styling_settings_navigation",
				'type'  => 'section',
				'panel' => 'styling_settings_panel',
				'title' => esc_html__( 'Primary Menu Styling', 'wildnest' ),
			),
			// a. Main Navigation
			array(
				'name'    		=> 'wildnest_styling_settings_main_navigation_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'title'   		=> esc_html__( 'Main Navigation', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_main_text_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'selector'   	=> '.builder-item--primary-menu .nav-menu-desktop .menu>li>a',
				'css_format' 	=> 'color: {{value}};',
				'title'      	=> esc_html__( 'Text Color', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_main_text_color_hover',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'selector'   	=> '.builder-item--primary-menu .nav-menu-desktop .menu>li>a:hover',
				'css_format' 	=> 'color: {{value}};',
				'title'      	=> esc_html__( 'Hover Text Color', 'wildnest' ),
			),
			// b. Submenu Navigation
			array(
				'name'    		=> 'wildnest_styling_settings_submenu_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'title'   		=> esc_html__( 'Submenus Styling', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_submenu_background',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'selector'    	=> ".nav-menu-desktop .sub-menu li a",
				'css_format' 	=> 'background-color: {{value}};',
				'title'      	=> esc_html__( 'Background Color', 'wildnest' ),
				'default'   	=> '#FFF',
			),
			array(
				'name'       	=> 'wildnest_styling_settings_submenu_text_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'selector'    	=> ".nav-menu-desktop .sub-menu li a",
				'css_format' 	=> 'color: {{value}};',
				'title'      	=> esc_html__( 'Text Color', 'wildnest' ),
				'default'   	=> '#484848',
			),
			array(
				'name'       	=> 'wildnest_styling_settings_submenu_background_hover',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'selector'    	=> ".nav-menu-desktop .sub-menu li a:hover",
				'css_format' 	=> 'background-color: {{value}};',
				'title'      	=> esc_html__( 'Hover Background Color', 'wildnest' ),
				'default'   	=> '#FFF',
			),
			array(
				'name'       	=> 'wildnest_styling_settings_submenu_text_color_hover',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'selector'    	=> ".nav-menu-desktop .sub-menu li a:hover",
				'css_format' 	=> 'color: {{value}};',
				'title'      	=> esc_html__( 'Hover Text Color', 'wildnest' ),
				'default'   	=> '#2695ff',
			),
			array(
				'name'       	=> 'wildnest_styling_settings_submenu_border_color_hover',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_navigation',
				'selector'    	=> ".nav-menu-desktop .sub-menu li",
				'css_format' 	=> 'border-bottom: 1px solid {{value}} !important;',
				'title'      	=> esc_html__( 'Border Color', 'wildnest' ),
				'default'   	=> '#ddd',
			),
			array(
				'name'        => 'wildnest_styling_settings_submenu_padding',
				'type'        => 'styling',
				'section'     => 'wildnest_styling_settings_navigation',
				'css_format'  => 'styling',
				'title'       => esc_html__( 'Styling Items', 'wildnest' ),
				'selector'    => array(
					'normal'            => ".nav-menu-desktop .sub-menu li a",
					'hover'             => ".nav-menu-desktop .sub-menu li a:hover"
				),
				'fields'      => array(
					'normal_fields' => array(
						'text_color'    => false,
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
						'border'		=> false,
						'border_radius' => false,
						'box_shadow' 	=> false,
						'border_style' 	=> false,
					),
					'hover_fields'  => array(
						'text_color'    => false,
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
						'border'		=> false,
						'border_radius' => false,
						'box_shadow' 	=> false,
						'border_style' 	=> false,
					),
				),
			),
			array(
				'name'        => 'wildnest_styling_settings_submenu_dropdown',
				'type'        => 'styling',
				'section'     => 'wildnest_styling_settings_navigation',
				'css_format'  => 'styling',
				'title'       => esc_html__( 'Styling Dropdown', 'wildnest' ),
				'selector'    => array(
					'normal'            => ".nav-menu-desktop .sub-menu",
					'hover'             => ".nav-menu-desktop .sub-menu:hover"
				),
				'fields'      => array(
					'normal_fields' => array(
						'text_color'    => false,
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
						'border'		=> false,
						'border_radius' => false,
						'box_shadow' 	=> false,
						'border_style' 	=> false,
					),
					'hover_fields'  => array(
						'text_color'    => false,
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
						'border'		=> false,
						'border_radius' => false,
						'box_shadow' 	=> false,
						'border_style' 	=> false,
					),
				),
			),

			// Mega Menu
			array(
				'name'  => "wildnest_styling_settings_mega_menu",
				'type'  => 'section',
				'panel' => 'styling_settings_panel',
				'title' => esc_html__( 'Mega Menu', 'wildnest' ),
			),
			// a. Main Navigation
			array(
				'name'    		=> 'wildnest_styling_settings_mega_menu_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_mega_menu',
				'title'   		=> esc_html__( 'Styling', 'wildnest' ),
			),
			array(
				'name'       	=> 'wildnest_styling_settings_mega_menu_color',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_mega_menu',
				'title'      	=> esc_html__( 'Links Color', 'wildnest' ),
				'selector'    	=> ".cf-mega-menu.sub-menu a",
				'css_format' 	=> 'color: {{value}};',
			),
			array(
				'name'       	=> 'wildnest_styling_settings_mega_menu_hover',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_mega_menu',
				'title'      	=> esc_html__( 'Links Hover', 'wildnest' ),
				'selector'    	=> ".cf-mega-menu.sub-menu a:hover",
				'css_format' 	=> 'color: {{value}};',
			),
			array(
				'name'            => 'wildnest_styling_settings_mega_menu_width',
				'type'            => 'slider',
				'device_settings' => true,
				'section' 		  => 'wildnest_styling_settings_mega_menu',
				'selector'        => ".cf-mega-menu.sub-menu",
				'css_format'      => 'width: {{value}};',
				'label'           => esc_html__( 'Width', 'wildnest' ),
			),

			// III. Buttons Tab
			array(
				'name'  => "wildnest_styling_settings_buttons",
				'type'  => 'section',
				'panel' => 'styling_settings_panel',
				'title' => esc_html__( 'Buttons', 'wildnest' ),
			),
			array(
				'name'        => "wildnest_styling_settings_buttons_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_buttons",
				'title'       => esc_html__( 'Typography', 'wildnest' ),
				'description' => esc_html__( 'Apply to buttons text.', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "{$wildnest_buttons}",
			), 
			array(
				'name'        => 'wildnest_styling_settings_buttons_styling',
				'type'        => 'styling',
				'section'     => 'wildnest_styling_settings_buttons',
				'css_format'  => 'styling',
				'title'       => esc_html__( 'Button Styling', 'wildnest' ),
				'selector'    => array(
					'normal'            => "{$wildnest_buttons}",
					'hover'             => "{$wildnest_buttons_hover}",
				),
				'fields'      => array(
					'normal_fields' => array(
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
					),
					'hover_fields'  => array(
						'link_color'    => false,
						'padding'       => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'border_radius' => false,
					),
				)
			),
			

			// IV. Fields Tab
			array(
				'name'  => "wildnest_styling_settings_fields",
				'type'  => 'section',
				'panel' => 'styling_settings_panel',
				'title' => esc_html__( 'Fields', 'wildnest' ),
			),
			array(
				'name'        => 'wildnest_styling_settings_fields_styling',
				'type'        => 'styling',
				'section'     => 'wildnest_styling_settings_fields',
				'css_format'  => 'styling',
				'title'       => esc_html__( 'Fields Styling', 'wildnest' ),
				'selector'    => array(
					'normal'            => "{$wildnest_fields}"
				),
				'fields'      => array(
					'normal_fields' => array(
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
					)
				)
			),
			array(
				'name'        => "wildnest_styling_settings_fields_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_fields",
				'title'       => esc_html__( 'Typography', 'wildnest' ),
				'description' => esc_html__( 'Apply to fields text.', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "{$wildnest_fields}",
			),
			array(
				'name'       	=> 'wildnest_styling_settings_fields_styling_focus',
				'type'       	=> 'color',
				'section' 		=> 'wildnest_styling_settings_fields',
				'selector'    	=> "{$wildnest_fields_focus}",
				'css_format' 	=> 'border-color: {{value}};',
				'title'      	=> esc_html__( 'Fields Color on Focus', 'wildnest' ),
				'default'   	=> '#d3d3d3',
			),
			// IV. Typography
			array(
				'name'  => "wildnest_styling_settings_typo",
				'type'  => 'section',
				'panel' => 'styling_settings_panel',
				'title' => esc_html__( 'Site Typography', 'wildnest' ),
			),
			array(
				'name'        => "wildnest_styling_settings_body_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Body Font family', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "body, ul li, ol li, p",
			),
			array(
				'name'        => "wildnest_styling_settings_h1_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H1', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "h1, h1 span",
			),
			array(
				'name'        => "wildnest_styling_settings_h2_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H2', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "h2",
			),
			array(
				'name'        => "wildnest_styling_settings_h3_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H3', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "h3, .post-name, .wildnest-post-name a",
			),
			array(
				'name'        => "wildnest_styling_settings_h4_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H4', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "h4",
			),
			array(
				'name'        => "wildnest_styling_settings_h5_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H5', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "h5",
			),
			array(
				'name'        => "wildnest_styling_settings_h6_typo",
				'type'        => 'typography',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H6', 'wildnest' ),
				'css_format'  => 'typography',
				'selector'    => "h6",
			),
			array(
				'name'    		=> 'wildnest_styling_settings_mobile_typo_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_typo',
				'title'   		=> esc_html__( 'Mobile Typography', 'wildnest' ),
			),
			array(
				'name'        => "wildnest_styling_settings_h1_size_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H1 Font size', 'wildnest' ),
				'default'	  => '26px',
			),
			array(
				'name'        => "wildnest_styling_settings_h1_lh_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H1 Line height', 'wildnest' ),
				'default'	  => '38px',
			),
			array(
				'name'        => "wildnest_styling_settings_h2_size_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H2 Font size', 'wildnest' ),
				'default'	  => '24px',
			),
			array(
				'name'        => "wildnest_styling_settings_h2_lh_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H2 Line height', 'wildnest' ),
				'default'	  => '28px',
			),
			array(
				'name'        => "wildnest_styling_settings_h3_size_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H3 Font size', 'wildnest' ),
				'default'	  => '22px',
			),
			array(
				'name'        => "wildnest_styling_settings_h3_lh_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H3 Line height', 'wildnest' ),
				'default'	  => '26px',
			),
			array(
				'name'        => "wildnest_styling_settings_h4_size_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H4 Font size', 'wildnest' ),
				'default'	  => '20px',
			),
			array(
				'name'        => "wildnest_styling_settings_h4_lh_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H4 Line height', 'wildnest' ),
				'default'	  => '24px',
			),
			array(
				'name'        => "wildnest_styling_settings_h5_size_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H5 Font size', 'wildnest' ),
				'default'	  => '18px',
			),
			array(
				'name'        => "wildnest_styling_settings_h5_lh_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H5 Line height', 'wildnest' ),
				'default'	  => '22px',
			),
			array(
				'name'        => "wildnest_styling_settings_h6_size_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H6 Font size', 'wildnest' ),
				'default'	  => '16px',
			),
			array(
				'name'        => "wildnest_styling_settings_h6_lh_mobile",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H6 Line height', 'wildnest' ),
				'default'	  => '20px',
			),
			array(
				'name'    		=> 'wildnest_styling_settings_tablet_typo_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_typo',
				'title'   		=> esc_html__( 'Tablet Typography', 'wildnest' ),
			),
			array(
				'name'        => "wildnest_styling_settings_h1_size_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H1 Font size', 'wildnest' ),
				'default'	  => '28px',
			),
			array(
				'name'        => "wildnest_styling_settings_h1_lh_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H1 Line height', 'wildnest' ),
				'default'	  => '32px',
			),
			array(
				'name'        => "wildnest_styling_settings_h2_size_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H2 Font size', 'wildnest' ),
				'default'	  => '26px',
			),
			array(
				'name'        => "wildnest_styling_settings_h2_lh_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H2 Line height', 'wildnest' ),
				'default'	  => '30px',
			),
			array(
				'name'        => "wildnest_styling_settings_h3_size_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H3 Font size', 'wildnest' ),
				'default'	  => '24px',
			),
			array(
				'name'        => "wildnest_styling_settings_h3_lh_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H3 Line height', 'wildnest' ),
				'default'	  => '28px',
			),
			array(
				'name'        => "wildnest_styling_settings_h4_size_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H4 Font size', 'wildnest' ),
				'default'	  => '22px',
			),
			array(
				'name'        => "wildnest_styling_settings_h4_lh_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H4 Line height', 'wildnest' ),
				'default'	  => '26px',
			),
			array(
				'name'        => "wildnest_styling_settings_h5_size_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H5 Font size', 'wildnest' ),
				'default'	  => '20px',
			),
			array(
				'name'        => "wildnest_styling_settings_h5_lh_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H5 Line height', 'wildnest' ),
				'default'	  => '23px',
			),
			array(
				'name'        => "wildnest_styling_settings_h6_size_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H6 Font size', 'wildnest' ),
				'default'	  => '18px',
			),
			array(
				'name'        => "wildnest_styling_settings_h6_lh_tablet",
				'type'        => 'text',
				'section'     => "wildnest_styling_settings_typo",
				'title'       => esc_html__( 'Heading H6 Line height', 'wildnest' ),
				'default'	  => '21px',
			),

			// IV. Typography
			array(
				'name'  	=> "wildnest_styling_settings_widgets",
				'type'  	=> 'section',
				'panel' 	=> 'styling_settings_panel',
				'title' 	=> esc_html__( 'Widgets Styling', 'wildnest' ),
			),
			array(
				'name'    	=> 'wildnest_styling_widgets_heading_1',
				'type'    	=> 'heading',
				'section' 	=> 'wildnest_styling_settings_widgets',
				'title'   	=> esc_html__( 'Sidebar Widgets', 'wildnest' ),
			),
			array(
				'name'        => 'wildnest_blog_widget_card_styling',
				'type'        => 'styling',
				'section'     => 'wildnest_styling_settings_widgets',
				'css_format'  => 'styling',
				'title'       => esc_html__( 'Card Styling', 'wildnest' ),
				'selector'    => '.sidebar-content .widget',
				'fields'      => array(
					'normal_fields' => array(
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
					)
				)
			),
			array(
				'name'        => 'wildnest_blog_sidebar_title_styling',
				'type'        => 'typography',
				'section'     => 'wildnest_styling_settings_widgets',
				'css_format'  => 'typography',
				'title'       => esc_html__( 'Title Typography', 'wildnest' ),
				'selector'    => '.sidebar-content .widget-title, .sidebar-content .widget h2, .sidebar-content .widget .wp-block-search__label'
			),
			array(
				'name'    		=> 'wildnest_styling_widgets_social_heading',
				'type'    		=> 'heading',
				'section' 		=> 'wildnest_styling_settings_widgets',
				'title'   		=> esc_html__( 'Widget: MT - Contact + Social Media', 'wildnest' ),
			),
			array(
				'name'        	=> 'wildnest_widget_contact_styling',
				'type'       	=> 'color',
				'section'     	=> 'wildnest_styling_settings_widgets',
				'title'       	=> esc_html__( 'Contact Links Styling', 'wildnest' ),
				'css_format' 	=> 'color: {{value}};',
				'selector'    	=> '.contact-details span, .contact-details span i',
			),
			array(
				'name'        	=> 'wildnest_widget_social_media_styling',
				'type'        	=> 'styling',
				'section'     	=> 'wildnest_styling_settings_widgets',
				'css_format'  	=> 'styling',
				'title'       	=> esc_html__( 'Social Icon Styling', 'wildnest' ),
				'selector'    	=> array(
					'normal'        => ".widget_mt_address_social_icons a",
					'hover'         => ".widget_mt_address_social_icons a:hover",
				),
				'fields'      	=> array(
					'normal_fields' => array(
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
					),
					'hover_fields'  => array(
						'link_color'    => false,
						'bg_cover'      => false,
						'bg_image'      => false,
						'bg_repeat'     => false,
						'bg_attachment' => false,
						'margin'        => false,
					)
				)
			)
		);

		return array_merge( $configs, $config );
	}
}

add_filter( 'wildnest/customizer/config', 'wildnest_customizer_styling_config' );
